services:
  - type: web
    name: yanli-intelligent-recruitment
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DEEPSEEK_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://uaegdgmzimtumivpjanm.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
